#!/usr/bin/env bash
# Rofi launcher wrapper.
# Launches rofi immediately without blocking on wallpaper cache or drun cache.
# The wallpaper thumbnail/blur is pre-generated by switchwall.sh when the
# wallpaper changes, so the cache is already fresh at launch time.
set -euo pipefail

pkill -x rofi 2>/dev/null || true
exec rofi -show drun -config "${HOME}/.config/rofi/config.rasi" "$@"
